language: ruby
sudo: false
os:
- linux
- osx
branches:
except:
- gh-pages
- next_doc_release
env:
  global:
    - LOGGING=true
rvm:
- jruby-19mode
before_install:
- gem update --system
- gem update bundler
script: rake ci